services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: quote-backend:dev
    container_name: quote-api
    environment:
      SERVER_PORT: ${API_PORT:-8080}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${API_PORT:-8080}/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    # domani (quando aggiungiamo DB):
    # depends_on:
    #   db:
    #     condition: service_healthy

  # Esempio (commentato) di Postgres per il prossimo step:
  # db:
  #   image: postgres:16
  #   container_name: quote-db
  #   environment:
  #     POSTGRES_USER: quote
  #     POSTGRES_PASSWORD: quote
  #     POSTGRES_DB: quote
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U quote -d quote"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 10

# volumi persistenti (per il DB quando lo useremo)
# volumes:
#   pgdata:
