name: backend-build-push

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-build-push.yml'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_BACKEND }}
          aws-region: eu-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Set image tags
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "TAG_SHA=main-${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          echo "TAG_LATEST=latest" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.ECR_REPOSITORY_URL }}:${{ steps.vars.outputs.TAG_SHA }}
            ${{ vars.ECR_REPOSITORY_URL }}:${{ steps.vars.outputs.TAG_LATEST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show pushed tags
        run: |
          echo "Pushed:"
          echo " - ${{ vars.ECR_REPOSITORY_URL }}:${{ steps.vars.outputs.TAG_SHA }}"
          echo " - ${{ vars.ECR_REPOSITORY_URL }}:${{ steps.vars.outputs.TAG_LATEST }}"
